# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: docs/images/

# The docker based version of this hook `hadolint-docker` does not work on M1 Macs
# -   repo: https://github.com/hadolint/hadolint
#     rev: v2.10.0
#     hooks:
#       - id: hadolint-docker
#
# Therefore we are using a hook which makes a direct call to
# `hadolint` locally installed. It may turn out that this is not a reasonable
# assumption for all developers machines. If necessary we might review this
# hook in due course.
-   repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint
        # The file `nginx/docker/Dockerfile` is a direct copy
        # from the nginxinc github repo, and hence has been excepted
        # from the pre-commit Dockerfile linting hook.
        # See docs/contributing.md#building-additional-nginx-modules
        # for more details
        exclude: nginx/docker/Dockerfile

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
