# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: docs/images/
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        exclude: jupyterlab/jupyter_server_config.py
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        exclude: jupyterlab/jupyter_server_config.py
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: (jupyterlab/jupyter_server_config.py|misc/print_banner.py)
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: v5.10.1
#     hooks:
#     -   id: isort
        # exclude: jupyterlab/jupyter_server_config.py


# The docker based version of this hook `hadolint-docker` does not work on M1 Macs
# -   repo: https://github.com/hadolint/hadolint
#     rev: v2.10.0
#     hooks:
#       - id: hadolint-docker
#
# Therefore we are using a hook which makes a direct call to
# `hadolint` locally installed. It may turn out that this is not a reasonable
# assumption for all developers machines. If necessary we might review this
# hook in due course.
-   repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
