# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# The docker based version of this hook `hadolint-docker` does not work on M1 Macs
# However we use it only for GitHub Actions linting
-   repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
        # The file `nginx/docker/Dockerfile` is a direct copy
        # from the nginxinc github repo, and hence has been excepted
        # from the pre-commit Dockerfile linting hook.
        # See docs/contributing.md#building-additional-nginx-modules
        # for more details
        exclude: nginx/docker/Dockerfile
