version: "3.9"

services:
  # long_app:
  #   image: node:12-alpine
  #   command: sh -c "yarn install && yarn run dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  dsnb:
    image: jupyter/scipy-notebook
    # container_name: jupyter
    command: start.sh jupyter lab  --LabApp.allow_remote_access='True' --LabApp.allow_origin='*'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: "yes"


    # image: jupyter/datascience-notebook:0fd03d9356de
    hostname: dsnb
    # ports:
    #   - 10001:8888
    working_dir: /notebooks
    networks:
      internal:
        aliases:
          - dsnb
    volumes:
      - ./unmanaged/:/notebooks
      - ./jupyterlab/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py

  webapp:
    build:
      context: ./app/
    hostname: webapp
    ports:
      - 5000:5000
    networks:
      internal:
        aliases:
          - webapp
    volumes:
      - ./app:/usr/src/app

  # See https://github.com/nginxinc/docker-nginx/tree/master/modules
  # For info on custom build of nginx
  webserver:
    hostname: webserver

    build:
      context: ./nginx/docker/
      args:
        ENABLED_MODULES: headers-more
    image: long-nginx
    ports:
      - 80:80
    networks:
      internal:
        aliases:
          - webserver
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/htpasswd_store:/etc/nginx/htpasswd_store
      # - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/static:/data/www
    depends_on:
      - dsnb

networks:
  internal: {}

# volumes:
#   todo-mysql-data:
